# Generated by Django 5.1.6 on 2025-02-27 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="video_channel",
            new_name="Channel",
        ),
    ]
