export const suggestionsArray = [
    // Bodybuilding
    "Best bodybuilding supplements for muscle growth",
    "How to start bodybuilding as a beginner",
    "Bodybuilding diet plan for cutting and bulking",
    "The best bodybuilding exercises for strength gains",
    "How to avoid injuries in bodybuilding workouts",
    "How to gain muscle fast with bodybuilding",
    "Best bodybuilding workout routines for beginners",
    "Understanding macronutrients in bodybuilding nutrition",
    "How to recover quickly from bodybuilding workouts",
    "Best warm-up and stretching routines for bodybuilding",
    "How to increase testosterone naturally for bodybuilding",
    "Best bodybuilding tips from professional trainers",
    "How to improve strength and endurance in bodybuilding",
    "Best gym equipment for home bodybuilding workouts",
    "How to track progress effectively in bodybuilding",

    // Music
    "Best music production software for beginners",
    "How to learn music theory step by step",
    "Top 10 must-learn instruments for musicians",
    "How to create a home studio for music recording",
    "Best microphones for professional music recording",
    "How to mix and master music like a pro",
    "Best headphones for music production and mixing",
    "How to write better lyrics for songwriting",
    "Understanding chords and scales in music composition",
    "How to start a career in the music industry",
    "Best free tools for digital music production",
    "How to record high-quality vocals at home",
    "Understanding different music genres and styles",
    "Best tips for performing live music on stage",
    "How to distribute music on streaming platforms",

    // Trade
    "How to master trade strategies in the stock market",
    "Best risk management techniques for trade beginners",
    "How to use technical indicators in trade analysis",
    "Understanding leverage and margin in trade",
    "Best books for learning trade psychology",
    "How to trade options in the stock market",
    "Understanding fundamental analysis in trading",
    "How to build a diversified trade portfolio",
    "Best trading apps and platforms for beginners",
    "How to trade forex like a professional",
    "Understanding candlestick patterns in trading",
    "How to use moving averages in technical trading",
    "Best day trading strategies for high profits",
    "How to avoid common trading mistakes",
    "Understanding swing trading vs. day trading",

    // Chess
    "How to improve your chess rating fast",
    "Best chess opening strategies for white and black",
    "How to analyze chess games like a grandmaster",
    "Top chess tactics to win more games",
    "Best chess endgame principles every player must know",
    "How to memorize chess openings effectively",
    "Best ways to practice chess without a board",
    "How to use chess puzzles to improve calculation skills",
    "Understanding the importance of pawn structure in chess",
    "Best chess strategies for rapid and blitz games",
    "How to develop a strong middle-game strategy in chess",
    "Best chess apps to play and learn online",
    "How to think like a grandmaster in chess",
    "How to counter aggressive chess openings",
    "Best defensive strategies in chess to avoid losing quickly",

    // Car
    "How to choose the best car for long-distance travel",
    "Best car maintenance tips to extend engine life",
    "Understanding car fuel efficiency and hybrid models",
    "How to diagnose car engine problems",
    "Best safety features to look for in a new car",
    "How to increase car horsepower effectively",
    "Best budget-friendly cars with great performance",
    "How to modify a car for better speed and handling",
    "Understanding automatic vs. manual transmission cars",
    "Best car insurance policies for new drivers",
    "How to detail and clean a car like a professional",
    "Best ways to improve fuel efficiency in any car",
    "Understanding the latest electric car technology",
    "How to change tires and perform basic car repairs",
    "Best car brands known for reliability and durability",

    // Rubik
    "How to solve a Rubik’s Cube in under 10 seconds",
    "Best Rubik’s Cube algorithms for beginners",
    "How to improve speedcubing techniques",
    "Understanding the advanced CFOP method for Rubik’s Cube",
    "Best 4x4 and 5x5 Rubik’s Cubes for speedcubing",
    "How to solve a Rubik’s Cube blindfolded",
    "Best online Rubik’s Cube timers for speedsolving",
    "How to lubricate and maintain a Rubik’s Cube",
    "Understanding different solving methods for Rubik’s Cube",
    "Best finger tricks to improve solving speed",
    "How to memorize algorithms faster in speedcubing",
    "Best competitions and events for Rubik’s Cube solvers",
    "How to solve a Megaminx cube easily",
    "Understanding color neutrality in Rubik’s Cube solving",
    "How to practice efficiently for Rubik’s Cube solving competitions",

    // AI
    "How to start an AI project with Python",
    "Best AI tools and libraries for deep learning",
    "Understanding machine learning algorithms in AI",
    "How AI is transforming the future of technology",
    "Best AI applications in healthcare and finance",
    "How to train an AI model for image recognition",
    "Understanding reinforcement learning in AI",
    "Best AI frameworks for building chatbots",
    "How to use AI for predictive analytics",
    "Understanding the ethical implications of AI",
    "Best courses to learn AI development online",
    "How AI is being used in self-driving cars",
    "Understanding natural language processing in AI",
    "How to optimize AI models for better accuracy",
    "Best datasets for training AI machine learning models",

    // CryptoCurrency
    "How to trade with MACD in cryptocurrency markets",
    "Best cryptocurrency wallets for secure storage",
    "Understanding blockchain technology in cryptocurrency",
    "Top 5 altcoins to invest in for 2025",
    "How to analyze Bitcoin price trends effectively",
    "How to stake crypto for passive income",
    "Best decentralized exchanges for crypto trading",
    "How to secure your crypto assets from hackers",
    "Understanding gas fees in Ethereum transactions",
    "How to use Binance for cryptocurrency trading",
    "Best tools for crypto market analysis",
    "How to invest in NFTs and digital assets",
    "Understanding smart contracts and DeFi",
    "How to identify good crypto projects before investing",
    "Best mobile apps for tracking cryptocurrency portfolios",

    // Animation
    "Best animation software for beginners in 2D and 3D",
    "How to create smooth character animation",
    "Understanding keyframes and timing in animation",
    "Best animation courses to learn online in 2025",
    "How to animate realistic movements in Blender",
    "Best techniques for lip-sync animation",
    "How to create frame-by-frame animations effectively",
    "Understanding the principles of motion in animation",
    "Best tools for creating short animated films",
    "How to storyboard for an animated movie",
    "Understanding rigging and skeletal animation",
    "Best animation industry trends to watch in 2025",
    "How to add special effects in 3D animations",
    "Understanding animation rendering techniques",
    "How to use AI to generate animated videos"
];
